-- 1. Create public.lessons table to store individual student attendance/details
CREATE TABLE IF NOT EXISTS public.lessons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  record_id BIGINT REFERENCES public.records(id) ON DELETE CASCADE,
  student_name TEXT NOT NULL,
  absent BOOLEAN DEFAULT FALSE
);

-- 2. Add 'absent' column to public.records (likely to indicate class-level absence status)
ALTER TABLE public.records 
ADD COLUMN IF NOT EXISTS absent BOOLEAN DEFAULT FALSE;
